In [1]:
import pandas as pd 
import numpy as np

## Google 太陽能板屋頂覆蓋資料

In [2]:

sunroof = pd.read_csv("/Users/christine_sieh/workspace/Electric price_caculator/#1 dataclean/project-sunroof-county-09082017.csv")
sunroof.head()

,region_name,state_name,lat_max,lat_min,lng_max,lng_min,lat_avg,lng_avg,yearly_sunlight_kwh_kw_threshold_avg,count_qualified,...,yearly_sunlight_kwh_n,yearly_sunlight_kwh_s,yearly_sunlight_kwh_e,yearly_sunlight_kwh_w,yearly_sunlight_kwh_f,yearly_sunlight_kwh_median,yearly_sunlight_kwh_total,install_size_kw_buckets_json,carbon_offset_metric_tons,existing_installs_count
0,NaN,NaN,32.551561,32.551527,-116.919812,-116.920318,32.551544,-116.920065,1299.65,2,...,4.745559e+03,7.692078e+03,0.000000e+00,0.000000e+00,0.000000e+00,5209.464685,1.243764e+04,"[[0,2]]",0.000000e+00,0
1,Acadia Parish,Louisiana,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.55,28,...,3.663058e+04,1.084676e+05,7.170529e+04,9.811702e+04,3.557943e+06,18455.689746,3.872863e+06,"[[0,5],[5,2],[10,5],[15,3],[20,2],[25,1],[40,1...",2.619893e+03,0
2,Ada County,Idaho,43.776411,43.297448,-115.998789,-116.512796,43.614095,-116.308027,1161.95,127097,...,4.510353e+07,7.928349e+08,3.305852e+08,5.466880e+08,9.644616e+08,12656.146387,2.679673e+09,"[[0,21743],[5,46490],[10,31665],[15,13302],[20...",7.125475e+05,333
3,Adams County,Colorado,40.000318,39.738577,-104.310944,-105.052979,39.879721,-104.923252,1250.35,103951,...,1.402637e+07,5.047118e+08,2.529707e+08,2.968862e+08,1.160027e+09,8740.831396,2.228622e+09,"[[0,37831],[5,40975],[10,12770],[15,4216],[20,...",1.356972e+06,2218
4,Aiken County,South Carolina,33.853912,33.271435,-81.276617,-82.007226,33.517511,-81.801685,1099.05,45852,...,6.609113e+07,2.521735e+08,1.524194e+08,1.672472e+08,2.772775e+08,12029.735608,9.152087e+08,"[[0,8380],[5,15615],[10,11092],[15,5170],[20,2...",5.372701e+05,84

#### 為了要使兩筆資料合併，把南加州與加州都同稱為加州

In [3]:
sunroof['state_name'] = sunroof['state_name'].replace(['South Carolina'],'CA')
sunroof.head()

,region_name,state_name,lat_max,lat_min,lng_max,lng_min,lat_avg,lng_avg,yearly_sunlight_kwh_kw_threshold_avg,count_qualified,...,yearly_sunlight_kwh_n,yearly_sunlight_kwh_s,yearly_sunlight_kwh_e,yearly_sunlight_kwh_w,yearly_sunlight_kwh_f,yearly_sunlight_kwh_median,yearly_sunlight_kwh_total,install_size_kw_buckets_json,carbon_offset_metric_tons,existing_installs_count
0,NaN,NaN,32.551561,32.551527,-116.919812,-116.920318,32.551544,-116.920065,1299.65,2,...,4.745559e+03,7.692078e+03,0.000000e+00,0.000000e+00,0.000000e+00,5209.464685,1.243764e+04,"[[0,2]]",0.000000e+00,0
1,Acadia Parish,Louisiana,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.55,28,...,3.663058e+04,1.084676e+05,7.170529e+04,9.811702e+04,3.557943e+06,18455.689746,3.872863e+06,"[[0,5],[5,2],[10,5],[15,3],[20,2],[25,1],[40,1...",2.619893e+03,0
2,Ada County,Idaho,43.776411,43.297448,-115.998789,-116.512796,43.614095,-116.308027,1161.95,127097,...,4.510353e+07,7.928349e+08,3.305852e+08,5.466880e+08,9.644616e+08,12656.146387,2.679673e+09,"[[0,21743],[5,46490],[10,31665],[15,13302],[20...",7.125475e+05,333
3,Adams County,Colorado,40.000318,39.738577,-104.310944,-105.052979,39.879721,-104.923252,1250.35,103951,...,1.402637e+07,5.047118e+08,2.529707e+08,2.968862e+08,1.160027e+09,8740.831396,2.228622e+09,"[[0,37831],[5,40975],[10,12770],[15,4216],[20,...",1.356972e+06,2218
4,Aiken County,CA,33.853912,33.271435,-81.276617,-82.007226,33.517511,-81.801685,1099.05,45852,...,6.609113e+07,2.521735e+08,1.524194e+08,1.672472e+08,2.772775e+08,12029.735608,9.152087e+08,"[[0,8380],[5,15615],[10,11092],[15,5170],[20,2...",5.372701e+05,84

### 為方便合併資料將全寫的州名改為縮寫的州名，再將它改為小寫

In [4]:
sunroof['state_name'] = sunroof['state_name'].replace(
    ['Alabama' ,'Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming'],

['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY']
)
sunroof.head()

,region_name,state_name,lat_max,lat_min,lng_max,lng_min,lat_avg,lng_avg,yearly_sunlight_kwh_kw_threshold_avg,count_qualified,...,yearly_sunlight_kwh_n,yearly_sunlight_kwh_s,yearly_sunlight_kwh_e,yearly_sunlight_kwh_w,yearly_sunlight_kwh_f,yearly_sunlight_kwh_median,yearly_sunlight_kwh_total,install_size_kw_buckets_json,carbon_offset_metric_tons,existing_installs_count
0,NaN,NaN,32.551561,32.551527,-116.919812,-116.920318,32.551544,-116.920065,1299.65,2,...,4.745559e+03,7.692078e+03,0.000000e+00,0.000000e+00,0.000000e+00,5209.464685,1.243764e+04,"[[0,2]]",0.000000e+00,0
1,Acadia Parish,LA,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.55,28,...,3.663058e+04,1.084676e+05,7.170529e+04,9.811702e+04,3.557943e+06,18455.689746,3.872863e+06,"[[0,5],[5,2],[10,5],[15,3],[20,2],[25,1],[40,1...",2.619893e+03,0
2,Ada County,ID,43.776411,43.297448,-115.998789,-116.512796,43.614095,-116.308027,1161.95,127097,...,4.510353e+07,7.928349e+08,3.305852e+08,5.466880e+08,9.644616e+08,12656.146387,2.679673e+09,"[[0,21743],[5,46490],[10,31665],[15,13302],[20...",7.125475e+05,333
3,Adams County,CO,40.000318,39.738577,-104.310944,-105.052979,39.879721,-104.923252,1250.35,103951,...,1.402637e+07,5.047118e+08,2.529707e+08,2.968862e+08,1.160027e+09,8740.831396,2.228622e+09,"[[0,37831],[5,40975],[10,12770],[15,4216],[20,...",1.356972e+06,2218
4,Aiken County,CA,33.853912,33.271435,-81.276617,-82.007226,33.517511,-81.801685,1099.05,45852,...,6.609113e+07,2.521735e+08,1.524194e+08,1.672472e+08,2.772775e+08,12029.735608,9.152087e+08,"[[0,8380],[5,15615],[10,11092],[15,5170],[20,2...",5.372701e+05,84

In [5]:
sunroof['state_name']=sunroof['state_name'].str.lower()
sunroof.head()

,region_name,state_name,lat_max,lat_min,lng_max,lng_min,lat_avg,lng_avg,yearly_sunlight_kwh_kw_threshold_avg,count_qualified,...,yearly_sunlight_kwh_n,yearly_sunlight_kwh_s,yearly_sunlight_kwh_e,yearly_sunlight_kwh_w,yearly_sunlight_kwh_f,yearly_sunlight_kwh_median,yearly_sunlight_kwh_total,install_size_kw_buckets_json,carbon_offset_metric_tons,existing_installs_count
0,NaN,NaN,32.551561,32.551527,-116.919812,-116.920318,32.551544,-116.920065,1299.65,2,...,4.745559e+03,7.692078e+03,0.000000e+00,0.000000e+00,0.000000e+00,5209.464685,1.243764e+04,"[[0,2]]",0.000000e+00,0
1,Acadia Parish,la,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.55,28,...,3.663058e+04,1.084676e+05,7.170529e+04,9.811702e+04,3.557943e+06,18455.689746,3.872863e+06,"[[0,5],[5,2],[10,5],[15,3],[20,2],[25,1],[40,1...",2.619893e+03,0
2,Ada County,id,43.776411,43.297448,-115.998789,-116.512796,43.614095,-116.308027,1161.95,127097,...,4.510353e+07,7.928349e+08,3.305852e+08,5.466880e+08,9.644616e+08,12656.146387,2.679673e+09,"[[0,21743],[5,46490],[10,31665],[15,13302],[20...",7.125475e+05,333
3,Adams County,co,40.000318,39.738577,-104.310944,-105.052979,39.879721,-104.923252,1250.35,103951,...,1.402637e+07,5.047118e+08,2.529707e+08,2.968862e+08,1.160027e+09,8740.831396,2.228622e+09,"[[0,37831],[5,40975],[10,12770],[15,4216],[20,...",1.356972e+06,2218
4,Aiken County,ca,33.853912,33.271435,-81.276617,-82.007226,33.517511,-81.801685,1099.05,45852,...,6.609113e+07,2.521735e+08,1.524194e+08,1.672472e+08,2.772775e+08,12029.735608,9.152087e+08,"[[0,8380],[5,15615],[10,11092],[15,5170],[20,2...",5.372701e+05,84

### 觀察資料型態

In [6]:

sunroof.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 910 entries, 0 to 909
Data columns (total 31 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   region_name                           909 non-null    object
 1   state_name                            909 non-null    object
 2   lat_max                               910 non-null    float64
 3   lat_min                               910 non-null    float64
 4   lng_max                               910 non-null    float64
 5   lng_min                               910 non-null    float64
 6   lat_avg                               910 non-null    float64
 7   lng_avg                               910 non-null    float64
 8   yearly_sunlight_kwh_kw_threshold_avg  910 non-null    float64
 9   count_qualified                       910 non-null    int64
 10  percent_covered                       910 non-null    float64
 11  percent_qualified                     910 non-null    float64
 12  number_of_panels_n                    910 non-null    int64
 13  number_of_panels_s                    910 non-null    int64
 14  number_of_panels_e                    910 non-null    int64
 15  number_of_panels_w                    910 non-null    int64
 16  number_of_panels_f                    910 non-null    int64
 17  number_of_panels_median               908 non-null    float64
 18  number_of_panels_total                908 non-null    float64
 19  kw_median                             908 non-null    float64
 20  kw_total                              908 non-null    float64
 21  yearly_sunlight_kwh_n                 910 non-null    float64
 22  yearly_sunlight_kwh_s                 910 non-null    float64
 23  yearly_sunlight_kwh_e                 910 non-null    float64
 24  yearly_sunlight_kwh_w                 910 non-null    float64
 25  yearly_sunlight_kwh_f                 910 non-null    float64
 26  yearly_sunlight_kwh_median            908 non-null    float64
 27  yearly_sunlight_kwh_total             908 non-null    float64
 28  install_size_kw_buckets_json          908 non-null    object
 29  carbon_offset_metric_tons             910 non-null    float64
 30  existing_installs_count               910 non-null    int64
dtypes: float64(21), int64(7), object(3)
memory usage: 220.5+ KB

## 匯入另一筆史丹佛的DeepSolar研究資料

In [7]:

deepsolar = pd.read_csv("/Users/christine_sieh/workspace/Electric price_caculator/#1 dataclean/deepsolar_tract.csv")
deepsolar.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 72537 entries, 0 to 72537
Columns: 168 entries, tile_count to avg_electricity_retail_rate
dtypes: bool(2), float64(111), int64(52), object(3)
memory usage: 92.6+ MB

把 Google太陽能屋頂的資料與 Stanford Deep Solar 兩個資料用`county`, `state`兩個欄位做雙重合併<br>因為發現不同州別也會有相同的鄉鎮名稱，所以必須用雙重條件合併欄位

In [8]:
deepsolar

,tile_count,solar_system_count,total_panel_area,fips,average_household_income,county,education_bachelor,education_college,education_doctoral,education_high_school_graduate,...,incentive_count_nonresidential,incentive_residential_state_level,incentive_nonresidential_state_level,net_metering,feedin_tariff,cooperate_tax,property_tax,sales_tax,rebate,avg_electricity_retail_rate
0,0,0,0.000000,27145011200,70352.78987,Stearns County,569,1690,13,1757,...,39,11,13,34,0,0,25,12,0,9.46
1,25,21,1133.436461,27145011301,61727.08520,Stearns County,674,1434,108,767,...,39,11,13,34,0,0,25,12,0,9.46
2,3,3,64.505776,27145011302,71496.88658,Stearns County,854,1459,31,1541,...,39,11,13,34,0,0,25,12,0,9.46
3,0,0,0.000000,27145011304,86840.15275,Stearns County,640,1116,68,1095,...,39,11,13,34,0,0,25,12,0,9.46
4,5,5,164.583303,27145011400,89135.31560,Stearns County,654,1314,15,982,...,39,11,13,34,0,0,25,12,0,9.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72533,1,1,40.277124,8049000202,90163.61186,Grand County,1612,1419,3,1099,...,50,12,15,11,0,0,10,11,0,9.82
72534,0,0,0.000000,40085094100,45124.15301,Love County,95,441,0,803,...,19,1,7,19,0,0,0,0,0,7.86
72535,1,1,21.902255,40085094200,60878.45874,Love County,426,961,11,1343,...,19,1,7,19,0,0,0,0,0,7.86
72536,0,0,0.000000,40085094300,56817.99687,Love County,134,355,5,571,...,19,1,7,19,0,0,0,0,0,7.86
72537,3,2,224.947000,48327950300,50221.55626,Menard County,137,457,0,470,...,54,3,5,0,0,0,36,0,0,8.66

In [9]:
deepsolar.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 72537 entries, 0 to 72537
Data columns (total 168 columns):
 #    Column                                   Dtype
---   ------                                   -----
 0    tile_count                               int64
 1    solar_system_count                       int64
 2    total_panel_area                         float64
 3    fips                                     int64
 4    average_household_income                 float64
 5    county                                   object
 6    education_bachelor                       int64
 7    education_college                        int64
 8    education_doctoral                       int64
 9    education_high_school_graduate           int64
 10   education_less_than_high_school          int64
 11   education_master                         int64
 12   education_population                     int64
 13   education_professional_school            int64
 14   employed                                 int64
 15   gini_index                               float64
 16   heating_fuel_coal_coke                   int64
 17   heating_fuel_electricity                 int64
 18   heating_fuel_fuel_oil_kerosene           int64
 19   heating_fuel_gas                         int64
 20   heating_fuel_housing_unit_count          int64
 21   heating_fuel_none                        int64
 22   heating_fuel_other                       int64
 23   heating_fuel_solar                       int64
 24   land_area                                float64
 25   per_capita_income                        float64
 26   population                               int64
 27   population_density                       float64
 28   poverty_family_below_poverty_level       int64
 29   poverty_family_count                     int64
 30   race_asian                               int64
 31   race_black_africa                        int64
 32   race_indian_alaska                       int64
 33   race_islander                            int64
 34   race_other                               int64
 35   race_two_more                            int64
 36   race_white                               int64
 37   state                                    object
 38   total_area                               float64
 39   unemployed                               int64
 40   water_area                               float64
 41   education_less_than_high_school_rate     float64
 42   education_high_school_graduate_rate      float64
 43   education_college_rate                   float64
 44   education_bachelor_rate                  float64
 45   education_master_rate                    float64
 46   education_professional_school_rate       float64
 47   education_doctoral_rate                  float64
 48   race_white_rate                          float64
 49   race_black_africa_rate                   float64
 50   race_indian_alaska_rate                  float64
 51   race_asian_rate                          float64
 52   race_islander_rate                       float64
 53   race_other_rate                          float64
 54   race_two_more_rate                       float64
 55   employ_rate                              float64
 56   poverty_family_below_poverty_level_rate  float64
 57   heating_fuel_gas_rate                    float64
 58   heating_fuel_electricity_rate            float64
 59   heating_fuel_fuel_oil_kerosene_rate      float64
 60   heating_fuel_coal_coke_rate              float64
 61   heating_fuel_solar_rate                  float64
 62   heating_fuel_other_rate                  float64
 63   heating_fuel_none_rate                   float64
 64   solar_panel_area_divided_by_area         float64
 65   solar_panel_area_per_capita              float64
 66   tile_count_residential                   int64
 67   tile_count_nonresidential                int64
 68   solar_system_count_residential           int64
 69   solar_system_count_nonresidential        int64
 70   total_panel_area_residential             float64
 71   total_panel_area_nonresidential          float64
 72   median_household_income                  float64
 73   electricity_price_residential            float64
 74   electricity_price_commercial             float64
 75   electricity_price_industrial             float64
 76   electricity_price_transportation         object
 77   electricity_price_overall                float64
 78   electricity_consume_residential          int64
 79   electricity_consume_commercial           int64
 80   electricity_consume_industrial           int64
 81   electricity_consume_total                int64
 82   household_count                          int64
 83   average_household_size                   float64
 84   housing_unit_count                       int64
 85   housing_unit_occupied_count              int64
 86   housing_unit_median_value                float64
 87   housing_unit_median_gross_rent           float64
 88   lat                                      float64
 89   lon                                      float64
 90   elevation                                float64
 91   heating_design_temperature               float64
 92   cooling_design_temperature               float64
 93   earth_temperature_amplitude              float64
 94   frost_days                               float64
 95   air_temperature                          float64
 96   relative_humidity                        float64
 97   daily_solar_radiation                    float64
 98   atmospheric_pressure                     float64
 99   wind_speed                               float64
 100  earth_temperature                        float64
 101  heating_degree_days                      float64
 102  cooling_degree_days                      float64
 103  age_18_24_rate                           float64
 104  age_25_34_rate                           float64
 105  age_more_than_85_rate                    float64
 106  age_75_84_rate                           float64
 107  age_35_44_rate                           float64
 108  age_45_54_rate                           float64
 109  age_65_74_rate                           float64
 110  age_55_64_rate                           float64
 111  age_10_14_rate                           float64
 112  age_15_17_rate                           float64
 113  age_5_9_rate                             float64
 114  household_type_family_rate               float64
 115  dropout_16_19_inschool_rate              float64
 116  occupation_construction_rate             float64
 117  occupation_public_rate                   float64
 118  occupation_information_rate              float64
 119  occupation_finance_rate                  float64
 120  occupation_education_rate                float64
 121  occupation_administrative_rate           float64
 122  occupation_manufacturing_rate            float64
 123  occupation_wholesale_rate                float64
 124  occupation_retail_rate                   float64
 125  occupation_transportation_rate           float64
 126  occupation_arts_rate                     float64
 127  occupation_agriculture_rate              float64
 128  occupancy_vacant_rate                    float64
 129  occupancy_owner_rate                     float64
 130  mortgage_with_rate                       float64
 131  transportation_home_rate                 float64
 132  transportation_car_alone_rate            float64
 133  transportation_walk_rate                 float64
 134  transportation_carpool_rate              float64
 135  transportation_motorcycle_rate           float64
 136  transportation_bicycle_rate              float64
 137  transportation_public_rate               float64
 138  travel_time_less_than_10_rate            float64
 139  travel_time_10_19_rate                   float64
 140  travel_time_20_29_rate                   float64
 141  travel_time_30_39_rate                   float64
 142  travel_time_40_59_rate                   float64
 143  travel_time_60_89_rate                   float64
 144  health_insurance_public_rate             float64
 145  health_insurance_none_rate               float64
 146  age_median                               float64
 147  travel_time_average                      float64
 148  voting_2016_dem_percentage               float64
 149  voting_2016_gop_percentage               float64
 150  voting_2016_dem_win                      bool
 151  voting_2012_dem_percentage               float64
 152  voting_2012_gop_percentage               float64
 153  voting_2012_dem_win                      bool
 154  number_of_years_of_education             float64
 155  diversity                                float64
 156  number_of_solar_system_per_household     float64
 157  incentive_count_residential              int64
 158  incentive_count_nonresidential           int64
 159  incentive_residential_state_level        int64
 160  incentive_nonresidential_state_level     int64
 161  net_metering                             int64
 162  feedin_tariff                            int64
 163  cooperate_tax                            int64
 164  property_tax                             int64
 165  sales_tax                                int64
 166  rebate                                   int64
 167  avg_electricity_retail_rate              float64
dtypes: bool(2), float64(111), int64(52), object(3)
memory usage: 92.6+ MB

In [10]:
solar_roof = sunroof.merge(deepsolar, how='inner', left_on=['region_name', 'state_name'], right_on=['county', 'state'])
solar_roof

,region_name,state_name,lat_max,lat_min,lng_max,lng_min,lat_avg,lng_avg,yearly_sunlight_kwh_kw_threshold_avg,count_qualified,...,incentive_count_nonresidential,incentive_residential_state_level,incentive_nonresidential_state_level,net_metering,feedin_tariff,cooperate_tax,property_tax,sales_tax,rebate,avg_electricity_retail_rate
0,Acadia Parish,la,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.550000,28,...,17,7,4,14,0,0,23,0,0,7.63
1,Acadia Parish,la,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.550000,28,...,17,7,4,14,0,0,23,0,0,7.63
2,Acadia Parish,la,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.550000,28,...,17,7,4,14,0,0,23,0,0,7.63
3,Acadia Parish,la,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.550000,28,...,17,7,4,14,0,0,23,0,0,7.63
4,Acadia Parish,la,30.480512,30.150698,-92.144065,-92.598066,30.256188,-92.331117,1073.550000,28,...,17,7,4,14,0,0,23,0,0,7.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56419,Yuma County,az,32.998227,32.097960,-113.342490,-114.791451,32.665432,-114.575738,1376.070522,36880,...,41,8,15,8,0,0,11,20,0,10.15
56420,Yuma County,az,32.998227,32.097960,-113.342490,-114.791451,32.665432,-114.575738,1376.070522,36880,...,41,8,15,8,0,0,11,20,0,10.15
56421,Yuma County,az,32.998227,32.097960,-113.342490,-114.791451,32.665432,-114.575738,1376.070522,36880,...,41,8,15,8,0,0,11,20,0,10.15
56422,Yuma County,az,32.998227,32.097960,-113.342490,-114.791451,32.665432,-114.575738,1376.070522,36880,...,41,8,15,8,0,0,11,20,0,10.15
56423,Yuma County,az,32.998227,32.097960,-113.342490,-114.791451,32.665432,-114.575738,1376.070522,36880,...,41,8,15,8,0,0,11,20,0,10.15

In [11]:
#check
solar_roof[['region_name','state_name','county','state']]

         region_name state_name         county state
0      Acadia Parish         la  Acadia Parish    la
1      Acadia Parish         la  Acadia Parish    la
2      Acadia Parish         la  Acadia Parish    la
3      Acadia Parish         la  Acadia Parish    la
4      Acadia Parish         la  Acadia Parish    la
...              ...        ...            ...   ...
56419    Yuma County         az    Yuma County    az
56420    Yuma County         az    Yuma County    az
56421    Yuma County         az    Yuma County    az
56422    Yuma County         az    Yuma County    az
56423    Yuma County         az    Yuma County    az

[56424 rows x 4 columns]

找出依變數(dependent variable)：y

`electricity_price_overall`(cents/kWh)$*$ `electricity_consume_total` (kWh)$*12$ <br> `Electricity_cost_total` 年度電費總花費(cents)

找出年度電價總花費額

In [12]:
solar_roof['electricity_cost_total']= (solar_roof['electricity_price_overall']*solar_roof['electricity_consume_total']*12)

1. `electricity_consume_residential`
2. `electricity_consume_commercial`
3. `electricity_consume_industrial`
4. `electricity_consume_total`<br>

太陽能預計發電量（google）的欄位是以年為單位 但是史丹佛 Deep solar 這四個欄位資料是用月份作為單位<br>
這4欄位的單位是用年去算出的平均數，把史丹佛 Deep solar 四個欄位的數字同乘12

方法參考pandas官網[05_add_columns](https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/05_add_columns.html)

## change the order of columns
put the y-value front of dataframe <br>
把想要預測的變數y (independent variable) 放在第一欄方便操作

In [13]:
solar_roof.insert(0, 'Electricity_cost_total', solar_roof['electricity_cost_total'])

In [14]:
solar_roof.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56424 entries, 0 to 56423
Data columns (total 201 columns):
 #    Column                                   Dtype
---   ------                                   -----
 0    Electricity_cost_total                   float64
 1    region_name                              object
 2    state_name                               object
 3    lat_max                                  float64
 4    lat_min                                  float64
 5    lng_max                                  float64
 6    lng_min                                  float64
 7    lat_avg                                  float64
 8    lng_avg                                  float64
 9    yearly_sunlight_kwh_kw_threshold_avg     float64
 10   count_qualified                          int64
 11   percent_covered                          float64
 12   percent_qualified                        float64
 13   number_of_panels_n                       int64
 14   number_of_panels_s                       int64
 15   number_of_panels_e                       int64
 16   number_of_panels_w                       int64
 17   number_of_panels_f                       int64
 18   number_of_panels_median                  float64
 19   number_of_panels_total                   float64
 20   kw_median                                float64
 21   kw_total                                 float64
 22   yearly_sunlight_kwh_n                    float64
 23   yearly_sunlight_kwh_s                    float64
 24   yearly_sunlight_kwh_e                    float64
 25   yearly_sunlight_kwh_w                    float64
 26   yearly_sunlight_kwh_f                    float64
 27   yearly_sunlight_kwh_median               float64
 28   yearly_sunlight_kwh_total                float64
 29   install_size_kw_buckets_json             object
 30   carbon_offset_metric_tons                float64
 31   existing_installs_count                  int64
 32   tile_count                               int64
 33   solar_system_count                       int64
 34   total_panel_area                         float64
 35   fips                                     int64
 36   average_household_income                 float64
 37   county                                   object
 38   education_bachelor                       int64
 39   education_college                        int64
 40   education_doctoral                       int64
 41   education_high_school_graduate           int64
 42   education_less_than_high_school          int64
 43   education_master                         int64
 44   education_population                     int64
 45   education_professional_school            int64
 46   employed                                 int64
 47   gini_index                               float64
 48   heating_fuel_coal_coke                   int64
 49   heating_fuel_electricity                 int64
 50   heating_fuel_fuel_oil_kerosene           int64
 51   heating_fuel_gas                         int64
 52   heating_fuel_housing_unit_count          int64
 53   heating_fuel_none                        int64
 54   heating_fuel_other                       int64
 55   heating_fuel_solar                       int64
 56   land_area                                float64
 57   per_capita_income                        float64
 58   population                               int64
 59   population_density                       float64
 60   poverty_family_below_poverty_level       int64
 61   poverty_family_count                     int64
 62   race_asian                               int64
 63   race_black_africa                        int64
 64   race_indian_alaska                       int64
 65   race_islander                            int64
 66   race_other                               int64
 67   race_two_more                            int64
 68   race_white                               int64
 69   state                                    object
 70   total_area                               float64
 71   unemployed                               int64
 72   water_area                               float64
 73   education_less_than_high_school_rate     float64
 74   education_high_school_graduate_rate      float64
 75   education_college_rate                   float64
 76   education_bachelor_rate                  float64
 77   education_master_rate                    float64
 78   education_professional_school_rate       float64
 79   education_doctoral_rate                  float64
 80   race_white_rate                          float64
 81   race_black_africa_rate                   float64
 82   race_indian_alaska_rate                  float64
 83   race_asian_rate                          float64
 84   race_islander_rate                       float64
 85   race_other_rate                          float64
 86   race_two_more_rate                       float64
 87   employ_rate                              float64
 88   poverty_family_below_poverty_level_rate  float64
 89   heating_fuel_gas_rate                    float64
 90   heating_fuel_electricity_rate            float64
 91   heating_fuel_fuel_oil_kerosene_rate      float64
 92   heating_fuel_coal_coke_rate              float64
 93   heating_fuel_solar_rate                  float64
 94   heating_fuel_other_rate                  float64
 95   heating_fuel_none_rate                   float64
 96   solar_panel_area_divided_by_area         float64
 97   solar_panel_area_per_capita              float64
 98   tile_count_residential                   int64
 99   tile_count_nonresidential                int64
 100  solar_system_count_residential           int64
 101  solar_system_count_nonresidential        int64
 102  total_panel_area_residential             float64
 103  total_panel_area_nonresidential          float64
 104  median_household_income                  float64
 105  electricity_price_residential            float64
 106  electricity_price_commercial             float64
 107  electricity_price_industrial             float64
 108  electricity_price_transportation         object
 109  electricity_price_overall                float64
 110  electricity_consume_residential          int64
 111  electricity_consume_commercial           int64
 112  electricity_consume_industrial           int64
 113  electricity_consume_total                int64
 114  household_count                          int64
 115  average_household_size                   float64
 116  housing_unit_count                       int64
 117  housing_unit_occupied_count              int64
 118  housing_unit_median_value                float64
 119  housing_unit_median_gross_rent           float64
 120  lat                                      float64
 121  lon                                      float64
 122  elevation                                float64
 123  heating_design_temperature               float64
 124  cooling_design_temperature               float64
 125  earth_temperature_amplitude              float64
 126  frost_days                               float64
 127  air_temperature                          float64
 128  relative_humidity                        float64
 129  daily_solar_radiation                    float64
 130  atmospheric_pressure                     float64
 131  wind_speed                               float64
 132  earth_temperature                        float64
 133  heating_degree_days                      float64
 134  cooling_degree_days                      float64
 135  age_18_24_rate                           float64
 136  age_25_34_rate                           float64
 137  age_more_than_85_rate                    float64
 138  age_75_84_rate                           float64
 139  age_35_44_rate                           float64
 140  age_45_54_rate                           float64
 141  age_65_74_rate                           float64
 142  age_55_64_rate                           float64
 143  age_10_14_rate                           float64
 144  age_15_17_rate                           float64
 145  age_5_9_rate                             float64
 146  household_type_family_rate               float64
 147  dropout_16_19_inschool_rate              float64
 148  occupation_construction_rate             float64
 149  occupation_public_rate                   float64
 150  occupation_information_rate              float64
 151  occupation_finance_rate                  float64
 152  occupation_education_rate                float64
 153  occupation_administrative_rate           float64
 154  occupation_manufacturing_rate            float64
 155  occupation_wholesale_rate                float64
 156  occupation_retail_rate                   float64
 157  occupation_transportation_rate           float64
 158  occupation_arts_rate                     float64
 159  occupation_agriculture_rate              float64
 160  occupancy_vacant_rate                    float64
 161  occupancy_owner_rate                     float64
 162  mortgage_with_rate                       float64
 163  transportation_home_rate                 float64
 164  transportation_car_alone_rate            float64
 165  transportation_walk_rate                 float64
 166  transportation_carpool_rate              float64
 167  transportation_motorcycle_rate           float64
 168  transportation_bicycle_rate              float64
 169  transportation_public_rate               float64
 170  travel_time_less_than_10_rate            float64
 171  travel_time_10_19_rate                   float64
 172  travel_time_20_29_rate                   float64
 173  travel_time_30_39_rate                   float64
 174  travel_time_40_59_rate                   float64
 175  travel_time_60_89_rate                   float64
 176  health_insurance_public_rate             float64
 177  health_insurance_none_rate               float64
 178  age_median                               float64
 179  travel_time_average                      float64
 180  voting_2016_dem_percentage               float64
 181  voting_2016_gop_percentage               float64
 182  voting_2016_dem_win                      bool
 183  voting_2012_dem_percentage               float64
 184  voting_2012_gop_percentage               float64
 185  voting_2012_dem_win                      bool
 186  number_of_years_of_education             float64
 187  diversity                                float64
 188  number_of_solar_system_per_household     float64
 189  incentive_count_residential              int64
 190  incentive_count_nonresidential           int64
 191  incentive_residential_state_level        int64
 192  incentive_nonresidential_state_level     int64
 193  net_metering                             int64
 194  feedin_tariff                            int64
 195  cooperate_tax                            int64
 196  property_tax                             int64
 197  sales_tax                                int64
 198  rebate                                   int64
 199  avg_electricity_retail_rate              float64
 200  electricity_cost_total                   float64
dtypes: bool(2), float64(134), int64(59), object(6)
memory usage: 86.2+ MB

### 丟掉不要的欄位
- 經緯度留一個就好
- 比率（rate）在資料裡具有高度重複性（number/總人口）

In [15]:
solar_roof = solar_roof.drop(columns=['lat_max','lat_min','lng_max','lng_min',
'percent_covered',
'percent_qualified','install_size_kw_buckets_json','tile_count','solar_system_count',
'state','education_less_than_high_school_rate','education_high_school_graduate_rate',
'education_college_rate','education_bachelor_rate','education_master_rate',
'education_professional_school_rate','education_doctoral_rate',
'race_white_rate','race_black_africa_rate','race_indian_alaska_rate','race_asian_rate','race_islander_rate',
'race_other_rate','race_two_more_rate','employ_rate','heating_fuel_gas_rate',
'heating_fuel_electricity_rate','heating_fuel_fuel_oil_kerosene_rate','heating_fuel_coal_coke_rate',
'heating_fuel_solar_rate','heating_fuel_other_rate','heating_fuel_none_rate','tile_count_residential',
'tile_count_nonresidential',
'electricity_price_residential',
'electricity_price_commercial',
'electricity_price_industrial',
'electricity_price_transportation',
'electricity_consume_residential',
'electricity_consume_commercial',
'electricity_consume_industrial',
'electricity_consume_total',
'number_of_solar_system_per_household',
'voting_2016_dem_win',
'voting_2012_dem_win',
'yearly_sunlight_kwh_total',
'number_of_panels_total',
'solar_panel_area_divided_by_area',
'electricity_cost_total',
'electricity_price_overall'])
solar_roof.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56424 entries, 0 to 56423
Data columns (total 151 columns):
 #    Column                                   Dtype
---   ------                                   -----
 0    Electricity_cost_total                   float64
 1    region_name                              object
 2    state_name                               object
 3    lat_avg                                  float64
 4    lng_avg                                  float64
 5    yearly_sunlight_kwh_kw_threshold_avg     float64
 6    count_qualified                          int64
 7    number_of_panels_n                       int64
 8    number_of_panels_s                       int64
 9    number_of_panels_e                       int64
 10   number_of_panels_w                       int64
 11   number_of_panels_f                       int64
 12   number_of_panels_median                  float64
 13   kw_median                                float64
 14   kw_total                                 float64
 15   yearly_sunlight_kwh_n                    float64
 16   yearly_sunlight_kwh_s                    float64
 17   yearly_sunlight_kwh_e                    float64
 18   yearly_sunlight_kwh_w                    float64
 19   yearly_sunlight_kwh_f                    float64
 20   yearly_sunlight_kwh_median               float64
 21   carbon_offset_metric_tons                float64
 22   existing_installs_count                  int64
 23   total_panel_area                         float64
 24   fips                                     int64
 25   average_household_income                 float64
 26   county                                   object
 27   education_bachelor                       int64
 28   education_college                        int64
 29   education_doctoral                       int64
 30   education_high_school_graduate           int64
 31   education_less_than_high_school          int64
 32   education_master                         int64
 33   education_population                     int64
 34   education_professional_school            int64
 35   employed                                 int64
 36   gini_index                               float64
 37   heating_fuel_coal_coke                   int64
 38   heating_fuel_electricity                 int64
 39   heating_fuel_fuel_oil_kerosene           int64
 40   heating_fuel_gas                         int64
 41   heating_fuel_housing_unit_count          int64
 42   heating_fuel_none                        int64
 43   heating_fuel_other                       int64
 44   heating_fuel_solar                       int64
 45   land_area                                float64
 46   per_capita_income                        float64
 47   population                               int64
 48   population_density                       float64
 49   poverty_family_below_poverty_level       int64
 50   poverty_family_count                     int64
 51   race_asian                               int64
 52   race_black_africa                        int64
 53   race_indian_alaska                       int64
 54   race_islander                            int64
 55   race_other                               int64
 56   race_two_more                            int64
 57   race_white                               int64
 58   total_area                               float64
 59   unemployed                               int64
 60   water_area                               float64
 61   poverty_family_below_poverty_level_rate  float64
 62   solar_panel_area_per_capita              float64
 63   solar_system_count_residential           int64
 64   solar_system_count_nonresidential        int64
 65   total_panel_area_residential             float64
 66   total_panel_area_nonresidential          float64
 67   median_household_income                  float64
 68   household_count                          int64
 69   average_household_size                   float64
 70   housing_unit_count                       int64
 71   housing_unit_occupied_count              int64
 72   housing_unit_median_value                float64
 73   housing_unit_median_gross_rent           float64
 74   lat                                      float64
 75   lon                                      float64
 76   elevation                                float64
 77   heating_design_temperature               float64
 78   cooling_design_temperature               float64
 79   earth_temperature_amplitude              float64
 80   frost_days                               float64
 81   air_temperature                          float64
 82   relative_humidity                        float64
 83   daily_solar_radiation                    float64
 84   atmospheric_pressure                     float64
 85   wind_speed                               float64
 86   earth_temperature                        float64
 87   heating_degree_days                      float64
 88   cooling_degree_days                      float64
 89   age_18_24_rate                           float64
 90   age_25_34_rate                           float64
 91   age_more_than_85_rate                    float64
 92   age_75_84_rate                           float64
 93   age_35_44_rate                           float64
 94   age_45_54_rate                           float64
 95   age_65_74_rate                           float64
 96   age_55_64_rate                           float64
 97   age_10_14_rate                           float64
 98   age_15_17_rate                           float64
 99   age_5_9_rate                             float64
 100  household_type_family_rate               float64
 101  dropout_16_19_inschool_rate              float64
 102  occupation_construction_rate             float64
 103  occupation_public_rate                   float64
 104  occupation_information_rate              float64
 105  occupation_finance_rate                  float64
 106  occupation_education_rate                float64
 107  occupation_administrative_rate           float64
 108  occupation_manufacturing_rate            float64
 109  occupation_wholesale_rate                float64
 110  occupation_retail_rate                   float64
 111  occupation_transportation_rate           float64
 112  occupation_arts_rate                     float64
 113  occupation_agriculture_rate              float64
 114  occupancy_vacant_rate                    float64
 115  occupancy_owner_rate                     float64
 116  mortgage_with_rate                       float64
 117  transportation_home_rate                 float64
 118  transportation_car_alone_rate            float64
 119  transportation_walk_rate                 float64
 120  transportation_carpool_rate              float64
 121  transportation_motorcycle_rate           float64
 122  transportation_bicycle_rate              float64
 123  transportation_public_rate               float64
 124  travel_time_less_than_10_rate            float64
 125  travel_time_10_19_rate                   float64
 126  travel_time_20_29_rate                   float64
 127  travel_time_30_39_rate                   float64
 128  travel_time_40_59_rate                   float64
 129  travel_time_60_89_rate                   float64
 130  health_insurance_public_rate             float64
 131  health_insurance_none_rate               float64
 132  age_median                               float64
 133  travel_time_average                      float64
 134  voting_2016_dem_percentage               float64
 135  voting_2016_gop_percentage               float64
 136  voting_2012_dem_percentage               float64
 137  voting_2012_gop_percentage               float64
 138  number_of_years_of_education             float64
 139  diversity                                float64
 140  incentive_count_residential              int64
 141  incentive_count_nonresidential           int64
 142  incentive_residential_state_level        int64
 143  incentive_nonresidential_state_level     int64
 144  net_metering                             int64
 145  feedin_tariff                            int64
 146  cooperate_tax                            int64
 147  property_tax                             int64
 148  sales_tax                                int64
 149  rebate                                   int64
 150  avg_electricity_retail_rate              float64
dtypes: float64(97), int64(51), object(3)
memory usage: 65.4+ MB

In [16]:
solar_roof = solar_roof.drop(columns=['county','poverty_family_below_poverty_level_rate','solar_panel_area_per_capita'])

## change the Dtype of column

把錯誤的資料類型改變

In [17]:
#solar_roof["voting_2016_dem_win"] = solar_roof["voting_2016_dem_win"].astype(int)
#solar_roof["voting_2012_dem_win"] = solar_roof["voting_2012_dem_win"].astype(int)
#solar_roof["elvectricity_price_transportation"] = pd.to_numeric(solar_roof["electricity_price_transportation"], errors='coerce')
#solar_roof[["voting_2016_dem_win","voting_2012_dem_win","electricity_price_transportation"]]

把NA丟掉和重複的丟掉

In [18]:

solar_roof = solar_roof.dropna()

In [19]:
solar_roof = solar_roof.drop_duplicates()

改名字

In [20]:
solar_roof.rename(columns={'state_name': 'state'}, inplace=True)
solar_roof.rename(columns={'region_name': 'county'}, inplace=True)

In [21]:
solar_roof.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41994 entries, 1 to 56423
Data columns (total 148 columns):
 #    Column                                Dtype
---   ------                                -----
 0    Electricity_cost_total                float64
 1    county                                object
 2    state                                 object
 3    lat_avg                               float64
 4    lng_avg                               float64
 5    yearly_sunlight_kwh_kw_threshold_avg  float64
 6    count_qualified                       int64
 7    number_of_panels_n                    int64
 8    number_of_panels_s                    int64
 9    number_of_panels_e                    int64
 10   number_of_panels_w                    int64
 11   number_of_panels_f                    int64
 12   number_of_panels_median               float64
 13   kw_median                             float64
 14   kw_total                              float64
 15   yearly_sunlight_kwh_n                 float64
 16   yearly_sunlight_kwh_s                 float64
 17   yearly_sunlight_kwh_e                 float64
 18   yearly_sunlight_kwh_w                 float64
 19   yearly_sunlight_kwh_f                 float64
 20   yearly_sunlight_kwh_median            float64
 21   carbon_offset_metric_tons             float64
 22   existing_installs_count               int64
 23   total_panel_area                      float64
 24   fips                                  int64
 25   average_household_income              float64
 26   education_bachelor                    int64
 27   education_college                     int64
 28   education_doctoral                    int64
 29   education_high_school_graduate        int64
 30   education_less_than_high_school       int64
 31   education_master                      int64
 32   education_population                  int64
 33   education_professional_school         int64
 34   employed                              int64
 35   gini_index                            float64
 36   heating_fuel_coal_coke                int64
 37   heating_fuel_electricity              int64
 38   heating_fuel_fuel_oil_kerosene        int64
 39   heating_fuel_gas                      int64
 40   heating_fuel_housing_unit_count       int64
 41   heating_fuel_none                     int64
 42   heating_fuel_other                    int64
 43   heating_fuel_solar                    int64
 44   land_area                             float64
 45   per_capita_income                     float64
 46   population                            int64
 47   population_density                    float64
 48   poverty_family_below_poverty_level    int64
 49   poverty_family_count                  int64
 50   race_asian                            int64
 51   race_black_africa                     int64
 52   race_indian_alaska                    int64
 53   race_islander                         int64
 54   race_other                            int64
 55   race_two_more                         int64
 56   race_white                            int64
 57   total_area                            float64
 58   unemployed                            int64
 59   water_area                            float64
 60   solar_system_count_residential        int64
 61   solar_system_count_nonresidential     int64
 62   total_panel_area_residential          float64
 63   total_panel_area_nonresidential       float64
 64   median_household_income               float64
 65   household_count                       int64
 66   average_household_size                float64
 67   housing_unit_count                    int64
 68   housing_unit_occupied_count           int64
 69   housing_unit_median_value             float64
 70   housing_unit_median_gross_rent        float64
 71   lat                                   float64
 72   lon                                   float64
 73   elevation                             float64
 74   heating_design_temperature            float64
 75   cooling_design_temperature            float64
 76   earth_temperature_amplitude           float64
 77   frost_days                            float64
 78   air_temperature                       float64
 79   relative_humidity                     float64
 80   daily_solar_radiation                 float64
 81   atmospheric_pressure                  float64
 82   wind_speed                            float64
 83   earth_temperature                     float64
 84   heating_degree_days                   float64
 85   cooling_degree_days                   float64
 86   age_18_24_rate                        float64
 87   age_25_34_rate                        float64
 88   age_more_than_85_rate                 float64
 89   age_75_84_rate                        float64
 90   age_35_44_rate                        float64
 91   age_45_54_rate                        float64
 92   age_65_74_rate                        float64
 93   age_55_64_rate                        float64
 94   age_10_14_rate                        float64
 95   age_15_17_rate                        float64
 96   age_5_9_rate                          float64
 97   household_type_family_rate            float64
 98   dropout_16_19_inschool_rate           float64
 99   occupation_construction_rate          float64
 100  occupation_public_rate                float64
 101  occupation_information_rate           float64
 102  occupation_finance_rate               float64
 103  occupation_education_rate             float64
 104  occupation_administrative_rate        float64
 105  occupation_manufacturing_rate         float64
 106  occupation_wholesale_rate             float64
 107  occupation_retail_rate                float64
 108  occupation_transportation_rate        float64
 109  occupation_arts_rate                  float64
 110  occupation_agriculture_rate           float64
 111  occupancy_vacant_rate                 float64
 112  occupancy_owner_rate                  float64
 113  mortgage_with_rate                    float64
 114  transportation_home_rate              float64
 115  transportation_car_alone_rate         float64
 116  transportation_walk_rate              float64
 117  transportation_carpool_rate           float64
 118  transportation_motorcycle_rate        float64
 119  transportation_bicycle_rate           float64
 120  transportation_public_rate            float64
 121  travel_time_less_than_10_rate         float64
 122  travel_time_10_19_rate                float64
 123  travel_time_20_29_rate                float64
 124  travel_time_30_39_rate                float64
 125  travel_time_40_59_rate                float64
 126  travel_time_60_89_rate                float64
 127  health_insurance_public_rate          float64
 128  health_insurance_none_rate            float64
 129  age_median                            float64
 130  travel_time_average                   float64
 131  voting_2016_dem_percentage            float64
 132  voting_2016_gop_percentage            float64
 133  voting_2012_dem_percentage            float64
 134  voting_2012_gop_percentage            float64
 135  number_of_years_of_education          float64
 136  diversity                             float64
 137  incentive_count_residential           int64
 138  incentive_count_nonresidential        int64
 139  incentive_residential_state_level     int64
 140  incentive_nonresidential_state_level  int64
 141  net_metering                          int64
 142  feedin_tariff                         int64
 143  cooperate_tax                         int64
 144  property_tax                          int64
 145  sales_tax                             int64
 146  rebate                                int64
 147  avg_electricity_retail_rate           float64
dtypes: float64(95), int64(51), object(2)
memory usage: 47.7+ MB

#輸出檔案

In [22]:
#solar_roof.to_csv('/Users/christine_sieh/workspace/Electric price_caculator/#1 dataclean/sunroof_train.csv')